import type { PageMeta } from "./types";

export const PAGES: PageMeta[] = [
  // Clubes
  { key: "Pontos_Totais", title: "Pontos Totais", category: "Clubes", mode: "rankings", kind: "table",
    description: "Soma bruta de Pts por época por equipa, com Total acumulado e média." },
  { key: "Pontos_Totais_Fixos", title: "Pontos Totais (Pesos Fixos)", category: "Clubes", mode: "rankings", kind: "table",
    description: "Pts ponderados pelo peso fixo da divisão (folha Pesos_Fixos), com Total." },
  { key: "Pontos_Totais_Dinamicos", title: "Pontos Totais (Pesos Dinâmicos)", category: "Clubes", mode: "rankings", kind: "table",
    description: "Pts ponderados pelo peso dinâmico calculado por divisão." },
  { key: "Coef_Clube", title: "Coeficiente de Clube", category: "Clubes", mode: "rankings", kind: "table",
    description: "Coeficiente sem peso, janela de 5 épocas ponderada (1.0–0.2)." },
  { key: "Coef_Clube_Fixos", title: "Coeficiente de Clube (Fixos)", category: "Clubes", mode: "rankings", kind: "table",
    description: "Coeficiente com peso fixo da divisão, janela 5 épocas." },
  { key: "Coef_Clube_Dinamicos", title: "Coeficiente de Clube (Dinâmicos)", category: "Clubes", mode: "rankings", kind: "table",
    description: "Coeficiente com peso dinâmico, janela 5 épocas." },
  { key: "Campeoes", title: "Histórico de Campeões", category: "Clubes", mode: "rankings", kind: "table",
    description: "Histórico de Campeões (C), Promovidos (P) e Despromovidos (D) por equipa." },
  { key: "Play_Off_Clubes", title: "Play-Off de Clubes", category: "Clubes", mode: "rankings", kind: "table",
    description: "Equipas em quase-subida (2º-5º div>1) e quase-título (1-2º div 1 sem título)." },
  { key: "Registo_Posicoes", title: "Registo de Posições", category: "Clubes", mode: "rankings", kind: "table",
    description: "Tabela equipa × época com posição final e tag (1C, 2P, etc)." },
  { key: "Evolucao_Pontos_Totais", title: "Evolução Pontos Totais", category: "Clubes", mode: "rankings", kind: "table",
    description: "Evolução de pontos por época com variações ano a ano." },
  { key: "Comparador_Clubes", title: "Comparador de Clubes", category: "Clubes", mode: "rankings", kind: "table",
    description: "Comparação lado a lado dos principais indicadores de clubes." },

  // Países
  { key: "Pontos_Total_Pais", title: "Pontos Total (Países)", category: "Países", mode: "rankings", kind: "table",
    description: "Soma de Pts por país por época, com Total." },
  { key: "Pontos_Media_Pais", title: "Pontos Média (Países)", category: "Países", mode: "rankings", kind: "table",
    description: "Média de Pts por país por época." },
  { key: "Coef_Paises", title: "Coeficiente de Países", category: "Países", mode: "rankings", kind: "table",
    description: "Coeficiente de países (janela 5 épocas, sem peso)." },
  { key: "Coef_Paises_Fixo", title: "Coeficiente de Países (Fixos)", category: "Países", mode: "rankings", kind: "table",
    description: "Coeficiente de países com pesos fixos." },
  { key: "Coef_Paises_Dinamico", title: "Coeficiente de Países (Dinâmicos)", category: "Países", mode: "rankings", kind: "table",
    description: "Coeficiente de países com pesos dinâmicos." },
  { key: "Sucesso_Paises", title: "Sucesso de Países", category: "Países", mode: "rankings", kind: "table",
    description: "Países por número de campeões, promovidos e total." },

  // Golos
  { key: "Golos_Marcados", title: "Golos Marcados", category: "Golos", mode: "rankings", kind: "table",
    description: "GM histórico por equipa por época, com Total." },
  { key: "Golos_Sofridos", title: "Golos Sofridos", category: "Golos", mode: "rankings", kind: "table",
    description: "GS histórico por equipa por época (ordenação ascendente)." },

  // Rankings Especiais
  { key: "Ranking_Underdogs", title: "Ranking Underdogs", category: "Rankings Especiais", mode: "rankings", kind: "table",
    description: "Eficiência: Pts / (GM + 1), média histórica." },
  { key: "Rising_Stars", title: "Rising Stars", category: "Rankings Especiais", mode: "rankings", kind: "table",
    description: "Crescimento: (v1-v2) + (v2-v3) das últimas 3 épocas." },
  { key: "Ranking_Muralha", title: "Ranking Muralha", category: "Rankings Especiais", mode: "rankings", kind: "table",
    description: "Solidez: GS / jogos da divisão (ordenação ascendente)." },
  { key: "Ranking_Rolo_Compressor", title: "Ranking Rolo Compressor", category: "Rankings Especiais", mode: "rankings", kind: "table",
    description: "Domínio: DG / (Pts + 1), média histórica." },

  // Divisões
  { key: "Stats_Divisoes", title: "Stats por Divisão", category: "Divisões", mode: "rankings", kind: "table",
    description: "Por divisão: desvio Pts, GM, DG, Força, Competitividade." },
  { key: "Pesos_Dinamicos", title: "Pesos Dinâmicos", category: "Divisões", mode: "rankings", kind: "table",
    description: "Peso por divisão = Força*0.7 + Comp*0.3, média histórica." },

  // Treinadores
  { key: "Ranking_Treinador", title: "Ranking Treinador", category: "Treinadores", mode: "treinadores", kind: "table",
    description: "Pts do clube mapeados ao treinador, ordenado por Total." },
  { key: "Ranking_Treinador_Fixos", title: "Ranking Treinador (Fixos)", category: "Treinadores", mode: "treinadores", kind: "table",
    description: "Pts ponderados (peso fixo) atribuídos ao treinador." },
  { key: "Ranking_Treinador_Pais", title: "Treinadores por País", category: "Treinadores", mode: "treinadores", kind: "table",
    description: "Soma de Pts por nacionalidade do treinador." },
  { key: "Ranking_Treinador_Pais_Fixo", title: "Treinadores por País (Fixos)", category: "Treinadores", mode: "treinadores", kind: "table",
    description: "Pts ponderados por nacionalidade do treinador." },
  { key: "Treinador_Campeoes", title: "Treinador Campeões", category: "Treinadores", mode: "treinadores", kind: "table",
    description: "Histórico de títulos e promoções por treinador." },
  { key: "Play_Off_Treinadores", title: "Play-Off Treinadores", category: "Treinadores", mode: "treinadores", kind: "table",
    description: "Treinadores com quase-subida e quase-título." },
  { key: "Treinador_Coef", title: "Treinador Coeficiente", category: "Treinadores", mode: "treinadores", kind: "table",
    description: "Coeficiente de treinador (janela 5 épocas)." },
  { key: "Treinador_Coef_Fixos", title: "Treinador Coeficiente (Fixos)", category: "Treinadores", mode: "treinadores", kind: "table",
    description: "Coeficiente de treinador com peso fixo." },

  // Posições Geral
  { key: "Posicoes_Coef_Clube_Fixos", title: "Coef. Clube (Fixos) - Valores Acumulados", category: "Posições Geral", mode: "rankings", kind: "table",
    description: "Valores acumulados do coeficiente de cada clube até cada época." },
  { key: "Posicoes_Treinador_Coef_Fixos", title: "Coef. Treinador (Fixos) - Valores Acumulados", category: "Posições Geral", mode: "treinadores", kind: "table",
    description: "Valores acumulados do coeficiente de cada treinador até cada época." },
  { key: "Posicoes_Ranking_Treinador", title: "Ranking Treinador - Valores Acumulados", category: "Posições Geral", mode: "treinadores", kind: "table",
    description: "Valores acumulados do ranking do treinador por época." },
  { key: "Posicoes_Ranking_Treinador_Fixos", title: "Ranking Treinador (Fixos) - Valores Acumulados", category: "Posições Geral", mode: "treinadores", kind: "table",
    description: "Valores acumulados do ranking do treinador com pesos fixos." },
  { key: "Posicoes_Pontos_Totais", title: "Pontos Totais - Valores Acumulados", category: "Posições Geral", mode: "rankings", kind: "table",
    description: "Valores acumulados de pontos totais por equipa até cada época." },
  { key: "Posicoes_Pontos_Totais_Fixos", title: "Pontos Totais (Fixos) - Valores Acumulados", category: "Posições Geral", mode: "rankings", kind: "table",
    description: "Valores acumulados de pontos totais ponderados por pesos fixos por equipa até cada época." },
  { key: "Ranking_Tendencia", title: "Tendência de Ranking", category: "Posições Geral", mode: "rankings", kind: "table",
    description: "Mudança de posição por equipa ao longo das épocas." },

  // Jogadores
  { key: "Rep_Atual_Clubes", title: "Reputação Atual (Clubes)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Média da R.A. dos top 28 jogadores (por C.A.) por clube." },
  { key: "Rep_Atual_Divisao", title: "Reputação Atual (Divisão)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Média da R.A. dos top 28 por divisão." },
  { key: "Rep_Mund_Clubes", title: "Reputação Mundial (Clubes)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Média da RM dos top 28 jogadores por clube." },
  { key: "Rep_Mund_Divisao", title: "Reputação Mundial (Divisão)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Média da RM dos top 28 por divisão." },
  { key: "CA_Clubes", title: "C.A. (Clubes)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Média de Capacidade Atual por clube (com Liga e divisão)." },
  { key: "CA_Divisao", title: "C.A. (Divisão)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Média de Capacidade Atual por divisão." },
  { key: "CP_Clubes", title: "C.P. (Clubes)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Média de Capacidade Potencial por clube." },
  { key: "CP_Divisao", title: "C.P. (Divisão)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Média de Capacidade Potencial por divisão." },
  { key: "Idade_Clubes", title: "Idade Média (Clubes)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Idade média dos jogadores por clube." },
  { key: "Idade_Divisao", title: "Idade Média (Divisão)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Idade média dos jogadores por divisão." },
  { key: "Salarios_Clubes", title: "Salários (Clubes)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Soma de salários (€/p.a.) por clube." },
  { key: "Salarios_Divisao", title: "Salários (Divisão)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Soma de salários por divisão." },
  { key: "VP_Clubes", title: "Valor de Plantel (Clubes)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Soma de Valor do Passe (M/m → milhões/milhares) por clube." },
  { key: "VP_Divisao", title: "Valor de Plantel (Divisão)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Soma de Valor do Passe por divisão." },
  { key: "Performance_Jogadores", title: "Performance de Jogadores", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Resumo de golos, assistências e desempenho por jogador." },
  { key: "Golos", title: "Golos (Jogadores)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Histórico de golos por jogador, com Total." },
  { key: "Assistencias", title: "Assistências (Jogadores)", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Histórico de assistências por jogador, com Total." },
  { key: "Contagem", title: "Contagem de Jogadores", category: "Jogadores", mode: "jogadores", kind: "table",
    description: "Número de jogadores por clube com Liga, Divisão, C.A., C.P., Salário e VP." },

  // Dashboards
  { key: "Dashboard_Clubes", title: "Dashboard Clubes", category: "Dashboards", mode: "rankings", kind: "dashboard",
    description: "Top 10 dos principais rankings de clubes." },
  { key: "Dashboard_Paises", title: "Dashboard Países", category: "Dashboards", mode: "rankings", kind: "dashboard",
    description: "Top 10 dos rankings de países." },
  { key: "Dashboard_Treinadores", title: "Dashboard Treinadores", category: "Dashboards", mode: "treinadores", kind: "dashboard",
    description: "Top 10 dos rankings de treinadores." },
  { key: "Dashboard_Jogadores", title: "Dashboard Jogadores", category: "Dashboards", mode: "jogadores", kind: "dashboard",
    description: "Top 10 de Golos e Assistências de jogadores." },
  { key: "Dashboard_Golos", title: "Dashboard Golos", category: "Dashboards", mode: "rankings", kind: "dashboard",
    description: "Top 10 de Golos Marcados e Golos Sofridos." },
  { key: "Resumo_Competicao", title: "Resumo da Competição", category: "Dashboards", mode: "rankings", kind: "table",
    description: "Resumo de métricas principais por época." },
  { key: "Mapa_Correlacao", title: "Mapa de Correlação", category: "Dashboards", mode: "rankings", kind: "table",
    description: "Correlação entre métricas de clubes e desempenho." },
  { key: "Mapa_Mundo", title: "Mapa Mundo", category: "Dashboards", mode: "always", kind: "dashboard",
    description: "Distribuição geográfica de top clubes e jogadores por país." },

  // Competições
  { key: "Super_League_Campeoes", title: "Super League — Histórico", category: "Competições", mode: "always", kind: "table",
    description: "Campeões, finalistas e pódios da Super League por clube." },
  { key: "Super_League_Treinadores", title: "Super League — Treinadores", category: "Competições", mode: "always", kind: "table",
    description: "Treinadores com mais títulos e pódios na Super League." },
  { key: "Super_League_Honras", title: "Super League — Honras por Época", category: "Competições", mode: "always", kind: "table",
    description: "Lista cronológica de todas as posições na Super League." },

  // Scouting
  { key: "scouting", title: "Scouting", category: "Scouting", mode: "always", kind: "scouting",
    description: "Perfil individual e comparador multi-entidade." },
];

export const PAGE_BY_KEY: Record<string, PageMeta> = Object.fromEntries(PAGES.map((p) => [p.key, p]));

export const CATEGORIES_ORDER: PageMeta["category"][] = [
  "Clubes",
  "Países",
  "Treinadores",
  "Posições Geral",
  "Jogadores",
  "Golos",
  "Rankings Especiais",
  "Divisões",
  "Competições",
  "Dashboards",
  "Scouting",
];