/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScoutingRouteImport } from './routes/scouting'
import { Route as MapaMundoRouteImport } from './routes/mapa-mundo'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as H2hRouteImport } from './routes/h2h'
import { Route as DominioRouteImport } from './routes/dominio'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabelaKeyRouteImport } from './routes/tabela.$key'
import { Route as DashboardKeyRouteImport } from './routes/dashboard.$key'
import { Route as ComparadorClubesRouteImport } from './routes/comparador.clubes'
import { Route as PerfilTreinadorNomeRouteImport } from './routes/perfil.treinador.$nome'
import { Route as PerfilPaisNomeRouteImport } from './routes/perfil.pais.$nome'
import { Route as PerfilJogadorNomeRouteImport } from './routes/perfil.jogador.$nome'
import { Route as PerfilClubeNomeRouteImport } from './routes/perfil.clube.$nome'

const ScoutingRoute = ScoutingRouteImport.update({
  id: '/scouting',
  path: '/scouting',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaMundoRoute = MapaMundoRouteImport.update({
  id: '/mapa-mundo',
  path: '/mapa-mundo',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const H2hRoute = H2hRouteImport.update({
  id: '/h2h',
  path: '/h2h',
  getParentRoute: () => rootRouteImport,
} as any)
const DominioRoute = DominioRouteImport.update({
  id: '/dominio',
  path: '/dominio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabelaKeyRoute = TabelaKeyRouteImport.update({
  id: '/tabela/$key',
  path: '/tabela/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardKeyRoute = DashboardKeyRouteImport.update({
  id: '/dashboard/$key',
  path: '/dashboard/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparadorClubesRoute = ComparadorClubesRouteImport.update({
  id: '/comparador/clubes',
  path: '/comparador/clubes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilTreinadorNomeRoute = PerfilTreinadorNomeRouteImport.update({
  id: '/perfil/treinador/$nome',
  path: '/perfil/treinador/$nome',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilPaisNomeRoute = PerfilPaisNomeRouteImport.update({
  id: '/perfil/pais/$nome',
  path: '/perfil/pais/$nome',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilJogadorNomeRoute = PerfilJogadorNomeRouteImport.update({
  id: '/perfil/jogador/$nome',
  path: '/perfil/jogador/$nome',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilClubeNomeRoute = PerfilClubeNomeRouteImport.update({
  id: '/perfil/clube/$nome',
  path: '/perfil/clube/$nome',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dominio': typeof DominioRoute
  '/h2h': typeof H2hRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/mapa-mundo': typeof MapaMundoRoute
  '/scouting': typeof ScoutingRoute
  '/comparador/clubes': typeof ComparadorClubesRoute
  '/dashboard/$key': typeof DashboardKeyRoute
  '/tabela/$key': typeof TabelaKeyRoute
  '/perfil/clube/$nome': typeof PerfilClubeNomeRoute
  '/perfil/jogador/$nome': typeof PerfilJogadorNomeRoute
  '/perfil/pais/$nome': typeof PerfilPaisNomeRoute
  '/perfil/treinador/$nome': typeof PerfilTreinadorNomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dominio': typeof DominioRoute
  '/h2h': typeof H2hRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/mapa-mundo': typeof MapaMundoRoute
  '/scouting': typeof ScoutingRoute
  '/comparador/clubes': typeof ComparadorClubesRoute
  '/dashboard/$key': typeof DashboardKeyRoute
  '/tabela/$key': typeof TabelaKeyRoute
  '/perfil/clube/$nome': typeof PerfilClubeNomeRoute
  '/perfil/jogador/$nome': typeof PerfilJogadorNomeRoute
  '/perfil/pais/$nome': typeof PerfilPaisNomeRoute
  '/perfil/treinador/$nome': typeof PerfilTreinadorNomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dominio': typeof DominioRoute
  '/h2h': typeof H2hRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/mapa-mundo': typeof MapaMundoRoute
  '/scouting': typeof ScoutingRoute
  '/comparador/clubes': typeof ComparadorClubesRoute
  '/dashboard/$key': typeof DashboardKeyRoute
  '/tabela/$key': typeof TabelaKeyRoute
  '/perfil/clube/$nome': typeof PerfilClubeNomeRoute
  '/perfil/jogador/$nome': typeof PerfilJogadorNomeRoute
  '/perfil/pais/$nome': typeof PerfilPaisNomeRoute
  '/perfil/treinador/$nome': typeof PerfilTreinadorNomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dominio'
    | '/h2h'
    | '/hall-of-fame'
    | '/mapa-mundo'
    | '/scouting'
    | '/comparador/clubes'
    | '/dashboard/$key'
    | '/tabela/$key'
    | '/perfil/clube/$nome'
    | '/perfil/jogador/$nome'
    | '/perfil/pais/$nome'
    | '/perfil/treinador/$nome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dominio'
    | '/h2h'
    | '/hall-of-fame'
    | '/mapa-mundo'
    | '/scouting'
    | '/comparador/clubes'
    | '/dashboard/$key'
    | '/tabela/$key'
    | '/perfil/clube/$nome'
    | '/perfil/jogador/$nome'
    | '/perfil/pais/$nome'
    | '/perfil/treinador/$nome'
  id:
    | '__root__'
    | '/'
    | '/dominio'
    | '/h2h'
    | '/hall-of-fame'
    | '/mapa-mundo'
    | '/scouting'
    | '/comparador/clubes'
    | '/dashboard/$key'
    | '/tabela/$key'
    | '/perfil/clube/$nome'
    | '/perfil/jogador/$nome'
    | '/perfil/pais/$nome'
    | '/perfil/treinador/$nome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DominioRoute: typeof DominioRoute
  H2hRoute: typeof H2hRoute
  HallOfFameRoute: typeof HallOfFameRoute
  MapaMundoRoute: typeof MapaMundoRoute
  ScoutingRoute: typeof ScoutingRoute
  ComparadorClubesRoute: typeof ComparadorClubesRoute
  DashboardKeyRoute: typeof DashboardKeyRoute
  TabelaKeyRoute: typeof TabelaKeyRoute
  PerfilClubeNomeRoute: typeof PerfilClubeNomeRoute
  PerfilJogadorNomeRoute: typeof PerfilJogadorNomeRoute
  PerfilPaisNomeRoute: typeof PerfilPaisNomeRoute
  PerfilTreinadorNomeRoute: typeof PerfilTreinadorNomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scouting': {
      id: '/scouting'
      path: '/scouting'
      fullPath: '/scouting'
      preLoaderRoute: typeof ScoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-mundo': {
      id: '/mapa-mundo'
      path: '/mapa-mundo'
      fullPath: '/mapa-mundo'
      preLoaderRoute: typeof MapaMundoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h2h': {
      id: '/h2h'
      path: '/h2h'
      fullPath: '/h2h'
      preLoaderRoute: typeof H2hRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dominio': {
      id: '/dominio'
      path: '/dominio'
      fullPath: '/dominio'
      preLoaderRoute: typeof DominioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabela/$key': {
      id: '/tabela/$key'
      path: '/tabela/$key'
      fullPath: '/tabela/$key'
      preLoaderRoute: typeof TabelaKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$key': {
      id: '/dashboard/$key'
      path: '/dashboard/$key'
      fullPath: '/dashboard/$key'
      preLoaderRoute: typeof DashboardKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparador/clubes': {
      id: '/comparador/clubes'
      path: '/comparador/clubes'
      fullPath: '/comparador/clubes'
      preLoaderRoute: typeof ComparadorClubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/treinador/$nome': {
      id: '/perfil/treinador/$nome'
      path: '/perfil/treinador/$nome'
      fullPath: '/perfil/treinador/$nome'
      preLoaderRoute: typeof PerfilTreinadorNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/pais/$nome': {
      id: '/perfil/pais/$nome'
      path: '/perfil/pais/$nome'
      fullPath: '/perfil/pais/$nome'
      preLoaderRoute: typeof PerfilPaisNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/jogador/$nome': {
      id: '/perfil/jogador/$nome'
      path: '/perfil/jogador/$nome'
      fullPath: '/perfil/jogador/$nome'
      preLoaderRoute: typeof PerfilJogadorNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/clube/$nome': {
      id: '/perfil/clube/$nome'
      path: '/perfil/clube/$nome'
      fullPath: '/perfil/clube/$nome'
      preLoaderRoute: typeof PerfilClubeNomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DominioRoute: DominioRoute,
  H2hRoute: H2hRoute,
  HallOfFameRoute: HallOfFameRoute,
  MapaMundoRoute: MapaMundoRoute,
  ScoutingRoute: ScoutingRoute,
  ComparadorClubesRoute: ComparadorClubesRoute,
  DashboardKeyRoute: DashboardKeyRoute,
  TabelaKeyRoute: TabelaKeyRoute,
  PerfilClubeNomeRoute: PerfilClubeNomeRoute,
  PerfilJogadorNomeRoute: PerfilJogadorNomeRoute,
  PerfilPaisNomeRoute: PerfilPaisNomeRoute,
  PerfilTreinadorNomeRoute: PerfilTreinadorNomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
